### ISSUE TITLE
Résoudre problème règle eci_1.2.4 en prod' pour les syndicats

### ISSUE THREAD

**Issue by Emelinejy** [betagouv/territoires-en-transitions#2418]
- [x] corrige l'identité donnée au moteur de calcul.
-----

# SITCOM Côte Sud
```yaml
habitants: 193 620
type: Syndicat
```

### Scores
```yaml
eci_1.2.2: 
  - desactive: true
eci_1.2.3: 
  - desactive: true
eci_1.2.4: 
  - base: 12.0
  - perso: 18.0
  - fait: 10.0
```

Erreurs pour la collectivité `SITCOM Côte Sud`
- `eci_1.2.2`: potentiel perso à `10.0` attendu `0.0` 
- `eci_1.2.3`: potentiel perso à `10.0` attendu `0.0` 
- `eci_1.2.4`: potentiel perso à `0.0` attendu `18.0` 
- `eci_1.2.2`: statut à `Fait` attendu `desactive` 
- `eci_1.2.3`: statut à `Fait` attendu `desactive` 
- `eci_1.2.4`: statut à `desactive` attendu `false`  ?

# Grenoble Alpes-Métropole
```yaml
habitants: 452 707
type: EPCI
```

## Réponses
```yaml
dev_eco_1: oui
```

### Scores
```yaml
eci_1.2.2: 
  - desactive: false
eci_1.2.3: 
  - desactive: false
eci_1.2.4: 
  - desactive: true  
```

Erreurs pour la collectivité `Grenoble Alpes-Métropole`
- `eci_1.2.2`: potentiel perso à `0.0` attendu `10.0` 
- `eci_1.2.3`: potentiel perso à `0.0` attendu `10.0` 
- `eci_1.2.4`: potentiel perso à `18.0` attendu `0.0` 

# Angers
```yaml
habitants: 158 930
type: commune
```

## Réponses
```yaml
dev_eco_1: non
```

### Scores
```yaml
eci_1.2.2: 
  - desactive: true
eci_1.2.3: 
  - desactive: true
eci_1.2.4: 
  - desactive: true  
```

Erreurs pour la collectivité `Angers`
- `eci_1.2.2`: potentiel perso à `10.0` attendu `0.0` 
- `eci_1.2.3`: potentiel perso à `10.0` attendu `0.0` 
- `eci_1.2.4`: potentiel perso à `18.0` attendu `0.0` 
- `eci_1.2.2`: statut à `Fait` attendu `desactive` 
- `eci_1.2.3`: statut à `Fait` attendu `desactive` 
- `eci_1.2.4`: statut à `Fait` attendu `desactive`
